using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "FruitItemDatabase", menuName = "Databases/Fruit Item Database")]
public class FruitItemDatabase : ScriptableObject
{
    [System.Serializable]
    public class FruitItemEntry
    {
        [Header("Identity")]
        public string itemID;
        public string displayName;
        public Sprite icon;
        public GameObject prefab;

        [Header("Stats")]
        public int hungerChange;
        public int hydrationChange;
        public float weight;
        public int maxStackSize;

        [Header("Disease Profile")]
        public float foodPoisoningChance;
        public float salmonellaChance;
        public float parasiteChance;
        public float zombiePathogenChance;

        [Header("Cooking")]
        public bool isCooked;
        public bool canBeBoiled;
        public bool canBeGrilled;
        public bool canBeRoasted;
        public bool canBeSteamed;
        public bool canBeFried;

        [Header("Slice & Seed Logic")]
        public bool canBeSliced;
        public int minSlices;
        public int maxSlices;
        public string secondaryItemID; // Seed ID
        public int minSecondaryYield;
        public int maxSecondaryYield;

        [Header("Tags")]
        public List<string> tags = new();
    }

    public List<FruitItemEntry> fruitItems = new()
    {
        // 🍏 Raw Green Apple
        new FruitItemEntry
        {
            itemID = "apple_green_raw",
            displayName = "Green Apple",
            icon = null,
            prefab = null,
            hungerChange = 10,
            hydrationChange = 5,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 3f,
            salmonellaChance = 0f,
            parasiteChance = 1f,
            zombiePathogenChance = 0f,
            isCooked = false,
            canBeBoiled = true,
            canBeGrilled = true,
            canBeRoasted = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 4,
            secondaryItemID = "apple_green_seeds",
            minSecondaryYield = 1,
            maxSecondaryYield = 9,
            tags = new() { "item", "food", "fruit", "raw", "apple", "hunger", "hydration" }
        },
        new FruitItemEntry
        {
            itemID = "apple_green_sliced",
            displayName = "Sliced Green Apple",
            icon = null,
            prefab = null,
            hungerChange = 8,
            hydrationChange = 4,
            weight = 0.28f,
            maxStackSize = 99,
            foodPoisoningChance = 2f,
            salmonellaChance = 0f,
            parasiteChance = 1f,
            zombiePathogenChance = 0f,
            isCooked = false,
            canBeBoiled = true,
            canBeGrilled = true,
            canBeRoasted = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "raw", "apple", "green", "sliced" }
        },

        // 🍽️ Cooked Variants – No seeds, not sliceable
        new FruitItemEntry
        {
            itemID = "apple_green_boiled",
            displayName = "Boiled Green Apple",
            icon = null,
            prefab = null,
            hungerChange = 12,
            hydrationChange = 4,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = true,
            canBeGrilled = false,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "boiled" }
        },

        new FruitItemEntry
        {
            itemID = "apple_green_grilled",
            displayName = "Grilled Green Apple",
            icon = null,
            prefab = null,
            hungerChange = 14,
            hydrationChange = 3,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = true,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "grilled" }
        },

        new FruitItemEntry
        {
            itemID = "apple_green_roasted",
            displayName = "Roasted Green Apple",
            icon = null,
            prefab = null,
            hungerChange = 13,
            hydrationChange = 2,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = false,
            canBeRoasted = true,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "roasted" }
        },

        new FruitItemEntry
        {
            itemID = "apple_green_fried",
            displayName = "Fried Green Apple",
            icon = null,
            prefab = null,
            hungerChange = 15,
            hydrationChange = 1,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = false,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "fried" }
        },

        // 🍎 Raw Red Apple
        new FruitItemEntry
        {
            itemID = "apple_red_raw",
            displayName = "Red Apple",
            icon = null,
            prefab = null,
            hungerChange = 11,
            hydrationChange = 6,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 2f,
            salmonellaChance = 0f,
            parasiteChance = 1f,
            zombiePathogenChance = 0f,
            isCooked = false,
            canBeBoiled = true,
            canBeGrilled = true,
            canBeRoasted = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 4,
            secondaryItemID = "apple_red_seeds",
            minSecondaryYield = 1,
            maxSecondaryYield = 9,
            tags = new() { "item", "food", "fruit", "raw", "apple", "hunger", "hydration" }
        },

        new FruitItemEntry
        {
            itemID = "apple_red_sliced",
            displayName = "Sliced Red Apple",
            icon = null,
            prefab = null,
            hungerChange = 9,
            hydrationChange = 4,
            weight = 0.30f,
            maxStackSize = 99,
            foodPoisoningChance = 2f,
            salmonellaChance = 0f,
            parasiteChance = 1f,
            zombiePathogenChance = 0f,
            isCooked = false,
            canBeBoiled = true,
            canBeGrilled = true,
            canBeRoasted = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "raw", "apple", "red", "sliced" }
        },

        // 🍽️ Cooked Red Apple Variants – No seeds, not sliceable
        new FruitItemEntry
        {
            itemID = "apple_red_boiled",
            displayName = "Boiled Red Apple",
            icon = null,
            prefab = null,
            hungerChange = 13,
            hydrationChange = 4,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = true,
            canBeGrilled = false,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "boiled" }
        },

        new FruitItemEntry
        {
            itemID = "apple_red_grilled",
            displayName = "Grilled Red Apple",
            icon = null,
            prefab = null,
            hungerChange = 15,
            hydrationChange = 3,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = true,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "grilled" }
        },

        new FruitItemEntry
        {
            itemID = "apple_red_roasted",
            displayName = "Roasted Red Apple",
            icon = null,
            prefab = null,
            hungerChange = 14,
            hydrationChange = 2,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = false,
            canBeRoasted = true,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "roasted" }
        },

        new FruitItemEntry
        {
            itemID = "apple_red_fried",
            displayName = "Fried Red Apple",
            icon = null,
            prefab = null,
            hungerChange = 16,
            hydrationChange = 1,
            weight = 0.4f,
            maxStackSize = 9,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = false,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "apple", "fried" }

        },
        // 🍐 Raw Pear
        new FruitItemEntry
        {
            itemID = "pear_raw",
            displayName = "Pear",
            icon = null,
            prefab = null,
            hungerChange = 9,
            hydrationChange = 7,
            weight = 0.35f,
            maxStackSize = 99,
            foodPoisoningChance = 2f,
            salmonellaChance = 0f,
            parasiteChance = 1f,
            zombiePathogenChance = 0f,
            isCooked = false,
            canBeBoiled = true,
            canBeGrilled = true,
            canBeRoasted = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 4,
            secondaryItemID = "pear_seeds",
            minSecondaryYield = 1,
            maxSecondaryYield = 4,
            tags = new() { "item", "food", "fruit", "raw", "pear", "hunger", "hydration" }

        },

        new FruitItemEntry
        {
            itemID = "pear_sliced",
            displayName = "Sliced Pear",
            icon = null,
            prefab = null,
            hungerChange = 9,
            hydrationChange = 5,
            weight = 0.30f,
            maxStackSize = 99,
            foodPoisoningChance = 2f,
            salmonellaChance = 0f,
            parasiteChance = 1f,
            zombiePathogenChance = 0f,
            isCooked = false,
            canBeBoiled = true,
            canBeGrilled = true,
            canBeRoasted = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeSliced = false, // Already sliced
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null, // Seeds already extracted
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "raw", "pear", "sliced", "hunger", "hydration" }
        },


        // 🍽️ Cooked Pear Variants – No seeds, not sliceable
        new FruitItemEntry
        {
            itemID = "pear_boiled",
            displayName = "Boiled Pear",
            icon = null,
            prefab = null,
            hungerChange = 11,
            hydrationChange = 5,
            weight = 0.35f,
            maxStackSize = 99,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = true,
            canBeGrilled = false,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "pear", "boiled" }
        },

        new FruitItemEntry
        {
            itemID = "pear_grilled",
            displayName = "Grilled Pear",
            icon = null,
            prefab = null,
            hungerChange = 13,
            hydrationChange = 4,
            weight = 0.35f,
            maxStackSize = 99,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = true,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "pear", "grilled" }
        },

        new FruitItemEntry
        {
            itemID = "pear_roasted",
            displayName = "Roasted Pear",
            icon = null,
            prefab = null,
            hungerChange = 12,
            hydrationChange = 3,
            weight = 0.35f,
            maxStackSize = 99,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = false,
            canBeRoasted = true,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "fruit", "cooked", "pear", "roasted" }
        },

        new FruitItemEntry
{
    itemID = "banana_raw",
    displayName = "Banana",
    icon = null,
    prefab = null,
    hungerChange = 10,
    hydrationChange = 5,
    weight = 0.25f,
    maxStackSize = 20,
    foodPoisoningChance = 0.1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "banana", "raw", "peelable" }
},

new FruitItemEntry
{
    itemID = "banana_grilled",
    displayName = "Grilled Banana",
    icon = null,
    prefab = null,
    hungerChange = 15,
    hydrationChange = 3,
    weight = 0.3f,
    maxStackSize = 10,
    foodPoisoningChance = 0.05f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "banana", "cooked", "grilled" }
},

new FruitItemEntry {
    itemID = "banana_fried",
    displayName = "Fried Banana",
    icon = null,
    prefab = null,
    hungerChange = 9,
    hydrationChange = 2,
    weight = 0.2f,
    maxStackSize = 20,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "banana", "cooked", "fried", "organic", "tropical", "cooking_result" }
},


new FruitItemEntry
{
    itemID = "orange_raw",
    displayName = "Orange",
    icon = null,
    prefab = null,
    hungerChange = 12,
    hydrationChange = 8,
    weight = 0.3f,
    maxStackSize = 20,
    foodPoisoningChance = 0.05f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = true,
    minSlices = 4,
    maxSlices = 8,
    secondaryItemID = "orange_seeds",
    minSecondaryYield = 1,
    maxSecondaryYield = 3,
    tags = new() { "item", "food", "fruit", "orange", "raw", "sliceable", "seeded", "peelable" }
},

new FruitItemEntry {
    itemID = "orange_sliced",
    displayName = "Sliced Orange",
    icon = null,
    prefab = null,
    hungerChange = 4,
    hydrationChange = 6,
    weight = 0.15f,
    maxStackSize = 40,
    foodPoisoningChance = 0.005f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "orange", "sliced", "prepared", "hydrating", "citrus" }
},


new FruitItemEntry {
    itemID = "tomato_red",
    displayName = "Red Tomato",
    icon = null,
    prefab = null,
    hungerChange = 8,
    hydrationChange = 6,
    weight = 0.15f,
    maxStackSize = 50,
    foodPoisoningChance = 0.03f,
    salmonellaChance = 0.01f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 3,
    maxSlices = 6,
    secondaryItemID = "tomato_seeds",
    minSecondaryYield = 2,
    maxSecondaryYield = 4,
    tags = new() { "item", "food", "fruit", "tomato", "red", "raw", "sliceable", "seeded", "vegetable-adjacent", "ripe" }
},

new FruitItemEntry {
    itemID = "tomato_red_sliced",
    displayName = "Sliced Red Tomato",
    icon = null,
    prefab = null,
    hungerChange = 3,
    hydrationChange = 5,
    weight = 0.12f,
    maxStackSize = 40,
    foodPoisoningChance = 0.01f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "tomato", "red", "sliced", "prepared", "hydrating", "vegetable_like" }
},


new FruitItemEntry {
    itemID = "tomato_green",
    displayName = "Green Tomato",
    icon = null,
    prefab = null,
    hungerChange = 4,
    hydrationChange = 3,
    weight = 0.15f,
    maxStackSize = 50,
    foodPoisoningChance = 0.05f,
    salmonellaChance = 0.02f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 3,
    maxSlices = 6,
    secondaryItemID = "tomato_seeds",
    minSecondaryYield = 2,
    maxSecondaryYield = 4,
    tags = new() { "item", "food", "fruit", "tomato", "green", "raw", "sliceable", "seeded", "vegetable-adjacent", "unripe" }
},
new FruitItemEntry {
    itemID = "tomato_green_sliced",
    displayName = "Sliced Green Tomato",
    icon = null,
    prefab = null,
    hungerChange = 2,
    hydrationChange = 4,
    weight = 0.12f,
    maxStackSize = 40,
    foodPoisoningChance = 0.015f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "tomato", "green", "sliced", "prepared", "hydrating", "vegetable_like" }
},


new FruitItemEntry {
    itemID = "tomato_red_grilled",
    displayName = "Grilled Red Tomato",
    icon = null,
    prefab = null,
    hungerChange = 10,
    hydrationChange = 4,
    weight = 0.12f,
    maxStackSize = 30,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "tomato", "red", "cooked", "grilled", "vegetable-adjacent", "ripe", "cooking_result" }
},
new FruitItemEntry {
    itemID = "tomato_red_roasted",
    displayName = "Roasted Red Tomato",
    icon = null,
    prefab = null,
    hungerChange = 9,
    hydrationChange = 3,
    weight = 0.12f,
    maxStackSize = 30,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "tomato", "red", "cooked", "roasted", "vegetable-adjacent", "ripe", "cooking_result" }
},
new FruitItemEntry {
    itemID = "tomato_green_grilled",
    displayName = "Grilled Green Tomato",
    icon = null,
    prefab = null,
    hungerChange = 5,
    hydrationChange = 2,
    weight = 0.12f,
    maxStackSize = 30,
    foodPoisoningChance = 0.02f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "tomato", "green", "cooked", "grilled", "vegetable-adjacent", "unripe", "cooking_result" }
},
new FruitItemEntry {
    itemID = "tomato_green_roasted",
    displayName = "Roasted Green Tomato",
    icon = null,
    prefab = null,
    hungerChange = 4,
    hydrationChange = 1,
    weight = 0.12f,
    maxStackSize = 30,
    foodPoisoningChance = 0.02f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "tomato", "green", "cooked", "roasted", "vegetable-adjacent", "unripe", "cooking_result" }
},

new FruitItemEntry {
    itemID = "peach_raw",
    displayName = "Peach",
    icon = null,
    prefab = null,
    hungerChange = 10,
    hydrationChange = 7,
    weight = 0.25f,
    maxStackSize = 20,
    foodPoisoningChance = 0.02f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = true,
    minSlices = 4,
    maxSlices = 6,
    secondaryItemID = "peach_seed",
    minSecondaryYield = 1,
    maxSecondaryYield = 1,
    tags = new() { "item", "food", "fruit", "peach", "raw", "sliceable", "seeded", "stone-fruit", "organic" }
},

new FruitItemEntry {
    itemID = "peach_sliced",
    displayName = "Sliced Peach",
    icon = null,
    prefab = null,
    hungerChange = 5,
    hydrationChange = 4,
    weight = 0.125f,
    maxStackSize = 30,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "peach", "sliced", "organic", "cooking_ingredient", "stone-fruit" }
},

new FruitItemEntry {
    itemID = "peach_grilled",
    displayName = "Grilled Peach",
    icon = null,
    prefab = null,
    hungerChange = 8,
    hydrationChange = 3,
    weight = 0.2f,
    maxStackSize = 30,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "peach", "cooked", "grilled", "stone-fruit", "cooking_result" }
},

new FruitItemEntry {
    itemID = "grapes_green",
    displayName = "Green Grapes",
    icon = null,
    prefab = null,
    hungerChange = 6,
    hydrationChange = 9,
    weight = 0.2f,
    maxStackSize = 40,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "grapes", "green", "raw", "seedless", "hydrating", "snackable" }
},
new FruitItemEntry {
    itemID = "grapes_red",
    displayName = "Red Grapes",
    icon = null,
    prefab = null,
    hungerChange = 7,
    hydrationChange = 8,
    weight = 0.2f,
    maxStackSize = 40,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "grapes", "red", "raw", "seedless", "hydrating", "snackable" }
},


new FruitItemEntry {
    itemID = "pumpkin_raw",
    displayName = "Pumpkin",
    icon = null,
    prefab = null,
    hungerChange = 14,
    hydrationChange = 5,
    weight = 0.5f,
    maxStackSize = 10,
    foodPoisoningChance = 0.02f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = true,
    minSlices = 6,
    maxSlices = 12,
    secondaryItemID = "pumpkin_seeds",
    minSecondaryYield = 3,
    maxSecondaryYield = 6,
    tags = new() { "item", "food", "fruit", "pumpkin", "raw", "sliceable", "seeded", "organic", "autumnal", "survival_stewable" }
},
new FruitItemEntry {
    itemID = "pumpkin_sliced",
    displayName = "Sliced Pumpkin",
    icon = null,
    prefab = null,
    hungerChange = 7,
    hydrationChange = 3,
    weight = 0.25f,
    maxStackSize = 20,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "pumpkin", "sliced", "organic", "cooking_ingredient", "autumnal", "survival_stewable" }
},
new FruitItemEntry {
    itemID = "pumpkin_grilled",
    displayName = "Grilled Pumpkin",
    icon = null,
    prefab = null,
    hungerChange = 12,
    hydrationChange = 2,
    weight = 0.4f,
    maxStackSize = 15,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "pumpkin", "cooked", "grilled", "organic", "autumnal", "cooking_result" }
},
new FruitItemEntry {
    itemID = "pumpkin_roasted",
    displayName = "Roasted Pumpkin",
    icon = null,
    prefab = null,
    hungerChange = 11,
    hydrationChange = 2,
    weight = 0.4f,
    maxStackSize = 15,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "pumpkin", "cooked", "roasted", "organic", "autumnal", "cooking_result" }
},

new FruitItemEntry {
    itemID = "cherry_black_raw",
    displayName = "Black Cherry",
    icon = null,
    prefab = null,
    hungerChange = 5,
    hydrationChange = 4,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.015f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 2,
    secondaryItemID = "cherry_seed",
    minSecondaryYield = 1,
    maxSecondaryYield = 1,
    tags = new() { "item", "food", "fruit", "cherry", "black", "raw", "sliceable", "seeded", "stone-fruit", "organic" }
},
new FruitItemEntry {
    itemID = "cherry_red_raw",
    displayName = "Red Cherry",
    icon = null,
    prefab = null,
    hungerChange = 6,
    hydrationChange = 4,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.015f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 2,
    secondaryItemID = "cherry_seed",
    minSecondaryYield = 1,
    maxSecondaryYield = 1,
    tags = new() { "item", "food", "fruit", "cherry", "red", "raw", "sliceable", "seeded", "stone-fruit", "organic" }
},
new FruitItemEntry {
    itemID = "cherry_black_boiled",
    displayName = "Boiled Black Cherry",
    icon = null,
    prefab = null,
    hungerChange = 7,
    hydrationChange = 2,
    weight = 0.1f,
    maxStackSize = 30,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "cherry", "black", "cooked", "boiled", "stone-fruit", "organic", "cooking_result" }
},
new FruitItemEntry {
    itemID = "cherry_red_boiled",
    displayName = "Boiled Red Cherry",
    icon = null,
    prefab = null,
    hungerChange = 8,
    hydrationChange = 2,
    weight = 0.1f,
    maxStackSize = 30,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "cherry", "red", "cooked", "boiled", "stone-fruit", "organic", "cooking_result" }
},

new FruitItemEntry {
    itemID = "melon_yellow_raw",
    displayName = "Yellow Melon",
    icon = null,
    prefab = null,
    hungerChange = 10,
    hydrationChange = 9,
    weight = 0.4f,
    maxStackSize = 15,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = true,
    minSlices = 4,
    maxSlices = 8,
    secondaryItemID = "melon_yellow_seeds",
    minSecondaryYield = 2,
    maxSecondaryYield = 4,
    tags = new() { "item", "food", "fruit", "melon", "yellow", "raw", "sliceable", "seeded", "hydrating", "organic", "summer" }
},
new FruitItemEntry {
    itemID = "melon_water_raw",
    displayName = "Watermelon",
    icon = null,
    prefab = null,
    hungerChange = 12,
    hydrationChange = 12,
    weight = 0.5f,
    maxStackSize = 10,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = true,
    minSlices = 6,
    maxSlices = 10,
    secondaryItemID = "melon_water_seeds",
    minSecondaryYield = 3,
    maxSecondaryYield = 6,
    tags = new() { "item", "food", "fruit", "melon", "watermelon", "raw", "sliceable", "seeded", "hydrating", "organic", "summer" }
},

new FruitItemEntry {
    itemID = "melon_yellow_sliced",
    displayName = "Sliced Yellow Melon",
    icon = null,
    prefab = null,
    hungerChange = 5,
    hydrationChange = 6,
    weight = 0.2f,
    maxStackSize = 20,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "melon", "yellow", "sliced", "hydrating", "organic", "summer", "snackable" }
},
new FruitItemEntry {
    itemID = "melon_water_sliced",
    displayName = "Sliced Watermelon",
    icon = null,
    prefab = null,
    hungerChange = 6,
    hydrationChange = 8,
    weight = 0.25f,
    maxStackSize = 20,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "melon", "watermelon", "sliced", "hydrating", "organic", "summer", "snackable" }
},

new FruitItemEntry {
    itemID = "strawberry_raw",
    displayName = "Strawberry",
    icon = null,
    prefab = null,
    hungerChange = 6,
    hydrationChange = 5,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = true,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "strawberry", "raw", "organic", "hydrating", "berry", "steamable" }
},
new FruitItemEntry {
    itemID = "strawberry_steamed",
    displayName = "Steamed Strawberry",
    icon = null,
    prefab = null,
    hungerChange = 8,
    hydrationChange = 3,
    weight = 0.1f,
    maxStackSize = 30,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = true,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "fruit", "strawberry", "cooked", "steamed", "organic", "berry", "cooking_result" }
}





    };
}
