using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "MeatItemDatabase", menuName = "Databases/Meat Item Database")]
public class MeatItemDatabase : ScriptableObject
{
    [System.Serializable]
    public class MeatItemEntry
    {
        [Header("Identity")]
        public string itemID;
        public string displayName;
        public Sprite icon;
        public GameObject prefab;

        [Header("Stats")]
        public int hungerChange;
        public int hydrationChange;
        public float weight;
        public int maxStackSize;

        [Header("Disease Profile")]
        public float foodPoisoningChance;
        public float salmonellaChance;
        public float parasiteChance;
        public float zombiePathogenChance;
        public float madCowChance;
        public float avianFluChance;
        public float cannibalDiseaseChance;

        [Header("Cooking")]
        public bool isCooked;
        public bool canBeBoiled;
        public bool canBeGrilled;
        public bool canBeRoasted;
        public bool canBeSteamed;
        public bool canBeFried;

        [Header("Slice & Bone Logic")]
        public bool canBeSliced;
        public int minSlices;
        public int maxSlices;
        public string secondaryItemID; // Bone or fat ID
        public int minSecondaryYield;
        public int maxSecondaryYield;

        [Header("Tags")]
        public List<string> tags = new();
    }

    public List<MeatItemEntry> meatItems = new()
    {
        // 🥩 Raw Beef
        new MeatItemEntry
        {
            itemID = "beef_raw",
            displayName = "Raw Beef",
            icon = null,
            prefab = null,
            hungerChange = 18,
            hydrationChange = -2,
            weight = 0.5f,
            maxStackSize = 5,
            foodPoisoningChance = 15f,
            salmonellaChance = 10f,
            parasiteChance = 5f,
            zombiePathogenChance = 0f,
            madCowChance = 5f,
            avianFluChance = 0f,
            cannibalDiseaseChance = 0f,
            isCooked = false,
            canBeBoiled = true,
            canBeGrilled = true,
            canBeRoasted = true,
            canBeSteamed = false,
            canBeFried = true,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 4,
            secondaryItemID = "beef_bone",
            minSecondaryYield = 1,
            maxSecondaryYield = 2,
            tags = new() { "item", "food", "meat", "raw", "beef", "protein", "sliceable", "organic", "dangerous" }
        },

        // 🔥 Grilled Beef
        new MeatItemEntry
        {
            itemID = "beef_grilled",
            displayName = "Grilled Beef",
            icon = null,
            prefab = null,
            hungerChange = 25,
            hydrationChange = -1,
            weight = 0.5f,
            maxStackSize = 5,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            madCowChance = 0f,
            avianFluChance = 0f,
            cannibalDiseaseChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = true,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "meat", "beef", "cooked", "grilled", "protein", "cooking_result" }
        },

        // 🍞 Baked Beef (Roasted Equivalent)
        new MeatItemEntry
        {
            itemID = "beef_baked",
            displayName = "Baked Beef",
            icon = null,
            prefab = null,
            hungerChange = 24,
            hydrationChange = -1,
            weight = 0.5f,
            maxStackSize = 5,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            madCowChance = 0f,
            avianFluChance = 0f,
            cannibalDiseaseChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = false,
            canBeRoasted = true,
            canBeSteamed = false,
            canBeFried = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "meat", "beef", "cooked", "baked", "protein", "cooking_result" }
        },

        // 🍳 Fried Beef
        new MeatItemEntry
        {
            itemID = "beef_fried",
            displayName = "Fried Beef",
            icon = null,
            prefab = null,
            hungerChange = 26,
            hydrationChange = -2,
            weight = 0.5f,
            maxStackSize = 5,
            foodPoisoningChance = 1f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            madCowChance = 0f,
            avianFluChance = 0f,
            cannibalDiseaseChance = 0f,
            isCooked = true,
            canBeBoiled = false,
            canBeGrilled = false,
            canBeRoasted = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new() { "item", "food", "meat", "beef", "cooked", "fried", "protein", "cooking_result" }
        },
        new MeatItemEntry
{
    itemID = "chicken_raw",
    displayName = "Raw Chicken",
    icon = null,
    prefab = null,
    hungerChange = 14,
    hydrationChange = -3,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 20f,
    salmonellaChance = 15f,
    parasiteChance = 3f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 10f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "chicken_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "chicken", "protein", "sliceable", "organic", "dangerous", "poultry" }
},
        new MeatItemEntry
{
    itemID = "chicken_boiled",
    displayName = "Boiled Chicken",
    icon = null,
    prefab = null,
    hungerChange = 18,
    hydrationChange = 0,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "chicken", "cooked", "boiled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "chicken_grilled",
    displayName = "Grilled Chicken",
    icon = null,
    prefab = null,
    hungerChange = 20,
    hydrationChange = -1,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "chicken", "cooked", "grilled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "chicken_roasted",
    displayName = "Roasted Chicken",
    icon = null,
    prefab = null,
    hungerChange = 19,
    hydrationChange = -1,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "chicken", "cooked", "roasted", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "chicken_fried",
    displayName = "Fried Chicken",
    icon = null,
    prefab = null,
    hungerChange = 22,
    hydrationChange = -2,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "chicken", "cooked", "fried", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "duck_raw",
    displayName = "Raw Duck",
    icon = null,
    prefab = null,
    hungerChange = 16,
    hydrationChange = -3,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 18f,
    salmonellaChance = 12f,
    parasiteChance = 4f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 12f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "duck_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "duck", "protein", "sliceable", "organic", "dangerous", "poultry" }
},
        new MeatItemEntry
{
    itemID = "duck_boiled",
    displayName = "Boiled Duck",
    icon = null,
    prefab = null,
    hungerChange = 20,
    hydrationChange = 0,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "duck", "cooked", "boiled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "duck_grilled",
    displayName = "Grilled Duck",
    icon = null,
    prefab = null,
    hungerChange = 22,
    hydrationChange = -1,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "duck", "cooked", "grilled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "duck_roasted",
    displayName = "Roasted Duck",
    icon = null,
    prefab = null,
    hungerChange = 21,
    hydrationChange = -1,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "duck", "cooked", "roasted", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "duck_fried",
    displayName = "Fried Duck",
    icon = null,
    prefab = null,
    hungerChange = 23,
    hydrationChange = -2,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "duck", "cooked", "fried", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "pheasant_raw",
    displayName = "Raw Pheasant",
    icon = null,
    prefab = null,
    hungerChange = 15,
    hydrationChange = -3,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 17f,
    salmonellaChance = 14f,
    parasiteChance = 4f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 10f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "pheasant_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "pheasant", "protein", "sliceable", "organic", "dangerous", "poultry" }
},
        new MeatItemEntry
{
    itemID = "pheasant_boiled",
    displayName = "Boiled Pheasant",
    icon = null,
    prefab = null,
    hungerChange = 19,
    hydrationChange = 0,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "pheasant", "cooked", "boiled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "pheasant_grilled",
    displayName = "Grilled Pheasant",
    icon = null,
    prefab = null,
    hungerChange = 21,
    hydrationChange = -1,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "pheasant", "cooked", "grilled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "pheasant_roasted",
    displayName = "Roasted Pheasant",
    icon = null,
    prefab = null,
    hungerChange = 20,
    hydrationChange = -1,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "pheasant", "cooked", "roasted", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "pheasant_fried",
    displayName = "Fried Pheasant",
    icon = null,
    prefab = null,
    hungerChange = 22,
    hydrationChange = -2,
    weight = 0.4f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "pheasant", "cooked", "fried", "protein", "poultry", "cooking_result" }
},new MeatItemEntry
{
    itemID = "turkey_raw",
    displayName = "Raw Turkey",
    icon = null,
    prefab = null,
    hungerChange = 20,
    hydrationChange = -3,
    weight = 0.6f,
    maxStackSize = 3,
    foodPoisoningChance = 20f,
    salmonellaChance = 15f,
    parasiteChance = 4f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 12f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 3,
    maxSlices = 6,
    secondaryItemID = "turkey_bone",
    minSecondaryYield = 2,
    maxSecondaryYield = 4,
    tags = new() { "item", "food", "meat", "raw", "turkey", "protein", "sliceable", "organic", "dangerous", "poultry" }
},
        new MeatItemEntry
{
    itemID = "turkey_boiled",
    displayName = "Boiled Turkey",
    icon = null,
    prefab = null,
    hungerChange = 24,
    hydrationChange = 0,
    weight = 0.6f,
    maxStackSize = 3,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "turkey", "cooked", "boiled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "turkey_grilled",
    displayName = "Grilled Turkey",
    icon = null,
    prefab = null,
    hungerChange = 26,
    hydrationChange = -1,
    weight = 0.6f,
    maxStackSize = 3,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "turkey", "cooked", "grilled", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "turkey_roasted",
    displayName = "Roasted Turkey",
    icon = null,
    prefab = null,
    hungerChange = 25,
    hydrationChange = -1,
    weight = 0.6f,
    maxStackSize = 3,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "turkey", "cooked", "roasted", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "turkey_fried",
    displayName = "Fried Turkey",
    icon = null,
    prefab = null,
    hungerChange = 28,
    hydrationChange = -2,
    weight = 0.6f,
    maxStackSize = 3,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "turkey", "cooked", "fried", "protein", "poultry", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "pork_raw",
    displayName = "Raw Pork",
    icon = null,
    prefab = null,
    hungerChange = 16,
    hydrationChange = -3,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 18f,
    salmonellaChance = 12f,
    parasiteChance = 15f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "pork_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "pork", "protein", "sliceable", "organic", "dangerous", "pig" }
},
        new MeatItemEntry
{
    itemID = "pork_grilled",
    displayName = "Grilled Pork",
    icon = null,
    prefab = null,
    hungerChange = 22,
    hydrationChange = -1,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "pork", "cooked", "grilled", "protein", "pig", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "pork_roasted",
    displayName = "Roasted Pork",
    icon = null,
    prefab = null,
    hungerChange = 21,
    hydrationChange = -1,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "pork", "cooked", "roasted", "protein", "pig", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "pork_fried",
    displayName = "Fried Pork",
    icon = null,
    prefab = null,
    hungerChange = 23,
    hydrationChange = -2,
    weight = 0.45f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "pork", "cooked", "fried", "protein", "pig", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "rabbit_raw",
    displayName = "Raw Rabbit",
    icon = null,
    prefab = null,
    hungerChange = 14,
    hydrationChange = -2,
    weight = 0.35f,
    maxStackSize = 5,
    foodPoisoningChance = 12f,
    salmonellaChance = 5f,
    parasiteChance = 10f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "rabbit_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "rabbit", "protein", "sliceable", "organic", "dangerous", "wild" }
},
        new MeatItemEntry
{
    itemID = "rabbit_grilled",
    displayName = "Grilled Rabbit",
    icon = null,
    prefab = null,
    hungerChange = 20,
    hydrationChange = -1,
    weight = 0.35f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "rabbit", "cooked", "grilled", "protein", "wild", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "rabbit_roasted",
    displayName = "Roasted Rabbit",
    icon = null,
    prefab = null,
    hungerChange = 19,
    hydrationChange = -1,
    weight = 0.35f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "rabbit", "cooked", "roasted", "protein", "wild", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "rabbit_fried",
    displayName = "Fried Rabbit",
    icon = null,
    prefab = null,
    hungerChange = 21,
    hydrationChange = -2,
    weight = 0.35f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "rabbit", "cooked", "fried", "protein", "wild", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "rabbit_boiled",
    displayName = "Boiled Rabbit",
    icon = null,
    prefab = null,
    hungerChange = 18,
    hydrationChange = 0,
    weight = 0.35f,
    maxStackSize = 5,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "rabbit", "cooked", "boiled", "protein", "wild", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "deer_raw",
    displayName = "Raw Deer",
    icon = null,
    prefab = null,
    hungerChange = 20,
    hydrationChange = -3,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 14f,
    salmonellaChance = 6f,
    parasiteChance = 12f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 5,
    secondaryItemID = "deer_bone",
    minSecondaryYield = 2,
    maxSecondaryYield = 3,
    tags = new() { "item", "food", "meat", "raw", "deer", "protein", "sliceable", "organic", "dangerous", "wild", "game" }
},
        new MeatItemEntry
{
    itemID = "deer_grilled",
    displayName = "Grilled Deer",
    icon = null,
    prefab = null,
    hungerChange = 26,
    hydrationChange = -1,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "deer", "cooked", "grilled", "protein", "wild", "game", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "deer_roasted",
    displayName = "Roasted Deer",
    icon = null,
    prefab = null,
    hungerChange = 25,
    hydrationChange = -1,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "deer", "cooked", "roasted", "protein", "wild", "game", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "deer_fried",
    displayName = "Fried Deer",
    icon = null,
    prefab = null,
    hungerChange = 27,
    hydrationChange = -2,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "deer", "cooked", "fried", "protein", "wild", "game", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "wolf_raw",
    displayName = "Raw Wolf Meat",
    icon = null,
    prefab = null,
    hungerChange = 18,
    hydrationChange = -3,
    weight = 0.45f,
    maxStackSize = 4,
    foodPoisoningChance = 20f,
    salmonellaChance = 8f,
    parasiteChance = 18f,
    zombiePathogenChance = 2f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "wolf_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "wolf", "protein", "sliceable", "organic", "dangerous", "wild", "predator" }
},
        new MeatItemEntry
{
    itemID = "wolf_grilled",
    displayName = "Grilled Wolf Meat",
    icon = null,
    prefab = null,
    hungerChange = 24,
    hydrationChange = -1,
    weight = 0.45f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "wolf", "cooked", "grilled", "protein", "wild", "predator", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "wolf_roasted",
    displayName = "Roasted Wolf Meat",
    icon = null,
    prefab = null,
    hungerChange = 23,
    hydrationChange = -1,
    weight = 0.45f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "wolf", "cooked", "roasted", "protein", "wild", "predator", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "wolf_fried",
    displayName = "Fried Wolf Meat",
    icon = null,
    prefab = null,
    hungerChange = 25,
    hydrationChange = -2,
    weight = 0.45f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "wolf", "cooked", "fried", "protein", "wild", "predator", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "bear_raw",
    displayName = "Raw Bear Meat",
    icon = null,
    prefab = null,
    hungerChange = 28,
    hydrationChange = -4,
    weight = 0.65f,
    maxStackSize = 3,
    foodPoisoningChance = 25f,
    salmonellaChance = 10f,
    parasiteChance = 22f,
    zombiePathogenChance = 3f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 5,
    secondaryItemID = "bear_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 3,
    tags = new() { "item", "food", "meat", "raw", "bear", "protein", "sliceable", "organic", "dangerous", "wild", "heavy" }
},
        new MeatItemEntry
{
    itemID = "bear_roasted",
    displayName = "Roasted Bear Meat",
    icon = null,
    prefab = null,
    hungerChange = 34,
    hydrationChange = -2,
    weight = 0.65f,
    maxStackSize = 3,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "bear", "cooked", "roasted", "protein", "wild", "heavy", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "bear_fried",
    displayName = "Fried Bear Meat",
    icon = null,
    prefab = null,
    hungerChange = 36,
    hydrationChange = -3,
    weight = 0.65f,
    maxStackSize = 3,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "bear", "cooked", "fried", "protein", "wild", "heavy", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "bear_grilled",
    displayName = "Grilled Bear Meat",
    icon = null,
    prefab = null,
    hungerChange = 35,
    hydrationChange = -2,
    weight = 0.65f,
    maxStackSize = 3,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "bear", "cooked", "grilled", "protein", "wild", "heavy", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "sheep_raw",
    displayName = "Raw Sheep Meat",
    icon = null,
    prefab = null,
    hungerChange = 20,
    hydrationChange = -2,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 12f,
    salmonellaChance = 6f,
    parasiteChance = 10f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = true,
    canBeGrilled = true,
    canBeRoasted = true,
    canBeSteamed = true,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "sheep_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "sheep", "protein", "sliceable", "organic", "domestic", "livestock" }
},
        new MeatItemEntry
{
    itemID = "sheep_grilled",
    displayName = "Grilled Sheep Meat",
    icon = null,
    prefab = null,
    hungerChange = 26,
    hydrationChange = -1,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "sheep", "cooked", "grilled", "protein", "domestic", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "sheep_roasted",
    displayName = "Roasted Sheep Meat",
    icon = null,
    prefab = null,
    hungerChange = 25,
    hydrationChange = -1,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "sheep", "cooked", "roasted", "protein", "domestic", "cooking_result" }
},
        new MeatItemEntry
{
    itemID = "sheep_fried",
    displayName = "Fried Sheep Meat",
    icon = null,
    prefab = null,
    hungerChange = 27,
    hydrationChange = -2,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "sheep", "cooked", "fried", "protein", "domestic", "cooking_result" }
},
new MeatItemEntry
{
    itemID = "sheep_boiled",
    displayName = "Boiled Sheep Meat",
    icon = null,
    prefab = null,
    hungerChange = 24,
    hydrationChange = +6,
    weight = 0.5f,
    maxStackSize = 4,
    foodPoisoningChance = 0.5f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = true,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "sheep", "cooked", "boiled", "protein", "hydrating", "domestic", "cooking_result" }
},
new MeatItemEntry
{
    itemID = "rat_raw",
    displayName = "Raw Rat Meat",
    icon = null,
    prefab = null,
    hungerChange = 8,
    hydrationChange = -2,
    weight = 0.2f,
    maxStackSize = 6,
    foodPoisoningChance = 30f,
    salmonellaChance = 12f,
    parasiteChance = 20f,
    zombiePathogenChance = 4f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = "rat_bone",
    minSecondaryYield = 0,
    maxSecondaryYield = 1,
    tags = new() { "item", "food", "meat", "raw", "rat", "protein", "urban", "scavenger", "dangerous", "small", "zombie_risk" }
},
new MeatItemEntry
{
    itemID = "rat_grilled",
    displayName = "Grilled Rat Meat",
    icon = null,
    prefab = null,
    hungerChange = 12,
    hydrationChange = -1,
    weight = 0.2f,
    maxStackSize = 6,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "rat", "cooked", "grilled", "protein", "urban", "scavenger", "cooking_result" }
},
new MeatItemEntry
{
    itemID = "rat_fried",
    displayName = "Fried Rat Meat",
    icon = null,
    prefab = null,
    hungerChange = 13,
    hydrationChange = -2,
    weight = 0.2f,
    maxStackSize = 6,
    foodPoisoningChance = 1f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 0f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "rat", "cooked", "fried", "protein", "urban", "scavenger", "cooking_result" }
},
new MeatItemEntry
{
    itemID = "human_raw",
    displayName = "Raw Human Meat",
    icon = null,
    prefab = null,
    hungerChange = 30,
    hydrationChange = -5,
    weight = 0.6f,
    maxStackSize = 2,
    foodPoisoningChance = 35f,
    salmonellaChance = 15f,
    parasiteChance = 25f,
    zombiePathogenChance = 6f,
    madCowChance = 2f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 12f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "human_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "human", "protein", "cannibal", "taboo", "dangerous", "psychological", "zombie_risk" }
},
new MeatItemEntry
{
    itemID = "human_grilled",
    displayName = "Grilled Human Meat",
    icon = null,
    prefab = null,
    hungerChange = 38,
    hydrationChange = -3,
    weight = 0.6f,
    maxStackSize = 2,
    foodPoisoningChance = 2f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 8f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "human", "cooked", "grilled", "protein", "cannibal", "taboo", "cooking_result" }
},
new MeatItemEntry
{
    itemID = "human_fried",
    displayName = "Fried Human Meat",
    icon = null,
    prefab = null,
    hungerChange = 40,
    hydrationChange = -4,
    weight = 0.6f,
    maxStackSize = 2,
    foodPoisoningChance = 2f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 0f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 8f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "human", "cooked", "fried", "protein", "cannibal", "taboo", "cooking_result" }
},
new MeatItemEntry
{
    itemID = "zombie_raw",
    displayName = "Raw Zombie Flesh",
    icon = null,
    prefab = null,
    hungerChange = 28,
    hydrationChange = -6,
    weight = 0.6f,
    maxStackSize = 2,
    foodPoisoningChance = 40f,
    salmonellaChance = 18f,
    parasiteChance = 30f,
    zombiePathogenChance = 25f,
    madCowChance = 3f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 18f,
    isCooked = false,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = true,
    minSlices = 2,
    maxSlices = 4,
    secondaryItemID = "zombie_bone",
    minSecondaryYield = 1,
    maxSecondaryYield = 2,
    tags = new() { "item", "food", "meat", "raw", "zombie", "protein", "cursed", "undead", "dangerous", "taboo", "zombie_risk" }
},new MeatItemEntry
{
    itemID = "zombie_grilled",
    displayName = "Grilled Zombie Flesh",
    icon = null,
    prefab = null,
    hungerChange = 36,
    hydrationChange = -4,
    weight = 0.6f,
    maxStackSize = 2,
    foodPoisoningChance = 2f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 12f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 12f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = true,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "zombie", "cooked", "grilled", "protein", "undead", "cursed", "cooking_result" }
},
new MeatItemEntry
{
    itemID = "zombie_fried",
    displayName = "Fried Zombie Flesh",
    icon = null,
    prefab = null,
    hungerChange = 38,
    hydrationChange = -5,
    weight = 0.6f,
    maxStackSize = 2,
    foodPoisoningChance = 2f,
    salmonellaChance = 0f,
    parasiteChance = 0f,
    zombiePathogenChance = 12f,
    madCowChance = 0f,
    avianFluChance = 0f,
    cannibalDiseaseChance = 12f,
    isCooked = true,
    canBeBoiled = false,
    canBeGrilled = false,
    canBeRoasted = false,
    canBeSteamed = false,
    canBeFried = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new() { "item", "food", "meat", "zombie", "cooked", "fried", "protein", "undead", "cursed", "cooking_result" }
}















































    };
}
