using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class VegetableItemEntry
{
    public string itemID;
    public string displayName;
    public Sprite icon;
    public GameObject prefab;

    public float hungerChange;
    public float hydrationChange;
    public float weight;
    public int maxStackSize;

    public float foodPoisoningChance;
    public float salmonellaChance;
    public float parasiteChance;
    public float zombiePathogenChance;

    public bool isCooked;

    public bool canBeSliced;
    public int minSlices;
    public int maxSlices;

    public bool canBeBoiled;
    public bool canBeSteamed;
    public bool canBeFried;
    public bool canBeRoasted;
    public bool canBeGrilled;

    public string secondaryItemID;
    public int minSecondaryYield;
    public int maxSecondaryYield;

    public List<string> tags;
}

[CreateAssetMenu(fileName = "VegetableItemDatabase", menuName = "Databases/Vegetable Item Database")]
public class VegetableItemDatabase : ScriptableObject
{
    public List<VegetableItemEntry> items = new List<VegetableItemEntry>()
    {
        new VegetableItemEntry
        {
            itemID = "red_onion_raw",
            displayName = "Red Onion",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 2,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0f,
            salmonellaChance = 0f,
            parasiteChance = 0f,
            zombiePathogenChance = 0f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 3,
            maxSlices = 6,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = "red_onion_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 2,
            tags = new List<string> { "item", "food", "vegetable", "onion", "red", "raw", "sliceable", "fryable", "plantable", "seed_source" }
        },
        new VegetableItemEntry
        {
            itemID = "red_onion_sliced",
            displayName = "Sliced Red Onion",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "onion", "red", "sliced", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "red_onion_fried",
            displayName = "Fried Red Onion",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 1,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "onion", "red", "cooked", "fried" }
        },
        new VegetableItemEntry
        {
            itemID = "white_onion_raw",
            displayName = "White Onion",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 2,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 3,
            maxSlices = 6,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = "white_onion_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 2,
            tags = new List<string> { "item", "food", "vegetable", "onion", "white", "raw", "sliceable", "fryable", "plantable", "seed_source" }
        },
        new VegetableItemEntry
        {
            itemID = "white_onion_sliced",
            displayName = "Sliced White Onion",
            icon = null,
            prefab = null,
            hungerChange = 1,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "onion", "white", "sliced", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "white_onion_fried",
            displayName = "Fried White Onion",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 1,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "onion", "white", "cooked", "fried" }
        },
        new VegetableItemEntry
        {
            itemID = "spring_onion_raw",
            displayName = "Spring Onion",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 3,
            weight = 0.15f,
            maxStackSize = 40,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 4,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = "spring_onion_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 2,
            tags = new List<string> { "item", "food", "vegetable", "onion", "spring", "raw", "sliceable", "fryable", "plantable", "seed_source" }
        },
        new VegetableItemEntry
        {
            itemID = "spring_onion_sliced",
            displayName = "Sliced Spring Onion",
            icon = null,
            prefab = null,
            hungerChange = 1,
            hydrationChange = 2,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "onion", "spring", "sliced", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "spring_onion_fried",
            displayName = "Fried Spring Onion",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 1,
            weight = 0.15f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "onion", "spring", "cooked", "fried" }
        },
        new VegetableItemEntry
        {
            itemID = "carrot_raw",
            displayName = "Carrot",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 3,
            weight = 0.15f,
            maxStackSize = 30,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 4,
            maxSlices = 8,
            canBeBoiled = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeRoasted = true,
            canBeGrilled = false,
            secondaryItemID = "carrot_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 3,
            tags = new List<string> { "item", "food", "vegetable", "carrot", "raw", "sliceable", "plantable", "seed_source" }
        },
        new VegetableItemEntry
        {
            itemID = "carrot_sliced",
            displayName = "Sliced Carrot",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 2,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "carrot", "sliced", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "carrot_steamed",
            displayName = "Steamed Carrot",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 2,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "carrot", "cooked", "steamed" }
        },
        new VegetableItemEntry
        {
            itemID = "carrot_boiled",
            displayName = "Boiled Carrot",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 3,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "carrot", "cooked", "boiled" }
        },
        new VegetableItemEntry
        {
            itemID = "potato_raw",
            displayName = "Potato",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 1,
            weight = 0.25f,
            maxStackSize = 25,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 3,
            maxSlices = 6,
            canBeBoiled = true,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = true,
            canBeGrilled = true,
            secondaryItemID = "potato_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 2,
            tags = new List<string> { "item", "food", "vegetable", "potato", "raw", "sliceable", "plantable", "seed_source" }
        },
        new VegetableItemEntry
        {
            itemID = "potato_boiled",
            displayName = "Boiled Potato",
            icon = null,
            prefab = null,
            hungerChange = 7,
            hydrationChange = 2,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.005f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "potato", "cooked", "boiled" }
        },
        new VegetableItemEntry
        {
            itemID = "potato_roasted",
            displayName = "Roasted Potato",
            icon = null,
            prefab = null,
            hungerChange = 8,
            hydrationChange = 1,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.003f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "potato", "cooked", "roasted" }
        },
        new VegetableItemEntry
        {
            itemID = "cucumber_raw",
            displayName = "Cucumber",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 6,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 4,
            maxSlices = 6,
            canBeSteamed = true,
            secondaryItemID = "cucumber_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 3,
            tags = new List<string> { "item", "food", "vegetable", "cucumber", "raw", "sliceable", "steamable", "seeded" }
        },
        new VegetableItemEntry
        {
            itemID = "cucumber_sliced",
            displayName = "Sliced Cucumber",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 4,
            weight = 0.12f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "cucumber", "sliced", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "cucumber_steamed",
            displayName = "Steamed Cucumber",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 3,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.003f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "cucumber", "cooked", "steamed" }
        },
        new VegetableItemEntry
        {
            itemID = "bell_pepper_raw",
            displayName = "Bell Pepper",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 4,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 3,
            maxSlices = 5,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = true,
            canBeGrilled = false,
            secondaryItemID = "bell_pepper_seed",
            minSecondaryYield = 2,
            maxSecondaryYield = 4,
            tags = new List<string> { "item", "food", "vegetable", "pepper", "bell", "raw", "sliceable", "roastable", "plantable", "seed_source" }
        },
        new VegetableItemEntry
        {
            itemID = "bell_pepper_sliced",
            displayName = "Sliced Bell Pepper",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 3,
            weight = 0.12f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "pepper", "bell", "sliced", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "bell_pepper_roasted",
            displayName = "Roasted Bell Pepper",
            icon = null,
            prefab = null,
            hungerChange = 6,
            hydrationChange = 2,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.003f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "pepper", "bell", "cooked", "roasted" }
        },
        new VegetableItemEntry
        {
            itemID = "broccoli_raw",
            displayName = "Broccoli",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 3,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = false,
            canBeSteamed = true,
            canBeGrilled = true,
            canBeRoasted = true,
            tags = new List<string> { "item", "food", "vegetable", "broccoli", "raw", "steamable", "grillable", "roastable" }
        },
        new VegetableItemEntry
        {
            itemID = "broccoli_steamed",
            displayName = "Steamed Broccoli",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 2,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "broccoli", "cooked", "steamed" }
        },
        new VegetableItemEntry
        {
            itemID = "broccoli_grilled",
            displayName = "Grilled Broccoli",
            icon = null,
            prefab = null,
            hungerChange = 6,
            hydrationChange = 1,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "broccoli", "cooked", "grilled" }
        },
        new VegetableItemEntry
        {
            itemID = "broccoli_roasted",
            displayName = "Roasted Broccoli",
            icon = null,
            prefab = null,
            hungerChange = 6,
            hydrationChange = 1,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            tags = new List<string> { "item", "food", "vegetable", "broccoli", "cooked", "roasted" }
        },
        new VegetableItemEntry
        {
            itemID = "leek_raw",
            displayName = "Leek",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 3,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0.008f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 5,
            canBeBoiled = true,
            canBeSteamed = true,
            canBeFried = false,
            canBeRoasted = true,
            canBeGrilled = true,
            secondaryItemID = "leek_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 2,
            tags = new List<string> { "item", "food", "vegetable", "leek", "raw", "sliceable", "plantable", "seed_source", "boilable", "steamed", "grillable", "roastable" }
        },
        new VegetableItemEntry
        {
            itemID = "leek_grilled",
            displayName = "Grilled Leek",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 1,
            weight = 0.2f,
            maxStackSize = 30,
            foodPoisoningChance = 0.001f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "leek", "grilled", "cooked", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_raw",
            displayName = "Garlic",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 4,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = true,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "raw", "sliceable", "fryable", "roastable", "plantable", "seedless" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_sliced",
            displayName = "Sliced Garlic",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = true,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "sliced", "raw", "fryable", "roastable", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_fried",
            displayName = "Fried Garlic",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 0,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "fried", "cooked", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_roasted",
            displayName = "Roasted Garlic",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.001f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "roasted", "cooked", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_raw",
            displayName = "Garlic",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 2,
            maxSlices = 4,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = true,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "raw", "sliceable", "fryable", "roastable", "plantable", "seedless" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_sliced",
            displayName = "Sliced Garlic",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = true,
            canBeRoasted = true,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "sliced", "raw", "fryable", "roastable", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_fried",
            displayName = "Fried Garlic",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 0,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "fried", "cooked", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "garlic_roasted",
            displayName = "Roasted Garlic",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 1,
            weight = 0.1f,
            maxStackSize = 40,
            foodPoisoningChance = 0.001f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "garlic", "roasted", "cooked", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "cabbage_raw",
            displayName = "Cabbage",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 4,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 4,
            maxSlices = 8,
            canBeBoiled = true,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = true,
            canBeGrilled = true,
            secondaryItemID = "cabbage_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 3,
            tags = new List<string> { "item", "food", "vegetable", "cabbage", "raw", "sliceable", "boilable", "roastable", "grillable", "plantable", "seed_source" }
        },
        new VegetableItemEntry
        {
            itemID = "cabbage_sliced",
            displayName = "Sliced Cabbage",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 3,
            weight = 0.2f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = true,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = true,
            canBeGrilled = true,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "cabbage", "sliced", "raw", "boilable", "roastable", "grillable", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "cabbage_boiled",
            displayName = "Boiled Cabbage",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 2,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "cabbage", "boiled", "cooked", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "cabbage_roasted",
            displayName = "Roasted Cabbage",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 1,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.001f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "cabbage", "roasted", "cooked", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "cabbage_grilled",
            displayName = "Grilled Cabbage",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 1,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.001f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "cabbage", "grilled", "cooked", "prepared" }
        },
        new VegetableItemEntry
        {
            itemID = "kale_raw",
            displayName = "Kale",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 3,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "kale", "raw", "boilable", "steammable", "fryable", "leafy", "nonplantable" }
        },

        new VegetableItemEntry
        {
            itemID = "kale_raw",
            displayName = "Kale",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 3,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "kale", "raw", "boilable", "steammable", "fryable", "leafy", "nonplantable" }
        },

        new VegetableItemEntry
        {
            itemID = "kale_boiled",
            displayName = "Boiled Kale",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 2,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "kale", "boiled", "cooked", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "kale_steamed",
            displayName = "Steamed Kale",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 2,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "kale", "steamed", "cooked", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "kale_fried",
            displayName = "Fried Kale",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 1,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "kale", "fried", "cooked", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "lettuce_raw",
            displayName = "Lettuce",
            icon = null,
            prefab = null,
            hungerChange = 2,
            hydrationChange = 4,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = true,
            minSlices = 4,
            maxSlices = 8,
            canBeBoiled = true,
            canBeSteamed = true,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = "lettuce_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 3,
            tags = new List<string> { "item", "food", "vegetable", "lettuce", "raw", "sliceable", "boilable", "steammable", "plantable", "seed_source" }
        },

        new VegetableItemEntry
        {
            itemID = "lettuce_sliced",
            displayName = "Sliced Lettuce",
            icon = null,
            prefab = null,
            hungerChange = 1,
            hydrationChange = 3,
            weight = 0.2f,
            maxStackSize = 40,
            foodPoisoningChance = 0.005f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = true,
            canBeSteamed = true,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "lettuce", "sliced", "raw", "boilable", "steammable", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "lettuce_steamed",
            displayName = "Steamed Lettuce",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 2,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "lettuce", "steamed", "cooked", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "lettuce_boiled",
            displayName = "Boiled Lettuce",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 2,
            weight = 0.25f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "lettuce", "boiled", "cooked", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "sweetcorn_raw",
            displayName = "Sweetcorn",
            icon = null,
            prefab = null,
            hungerChange = 3,
            hydrationChange = 2,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.01f,
            isCooked = false,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = true,
            canBeSteamed = true,
            canBeFried = true,
            canBeRoasted = true,
            canBeGrilled = true,
            secondaryItemID = "sweetcorn_seed",
            minSecondaryYield = 1,
            maxSecondaryYield = 2,
            tags = new List<string> { "item", "food", "vegetable", "sweetcorn", "raw", "boilable", "roastable", "grillable", "fryable", "plantable", "seed_source" }
        },

        new VegetableItemEntry
        {
            itemID = "sweetcorn_boiled",
            displayName = "Boiled Sweetcorn",
            icon = null,
            prefab = null,
            hungerChange = 4,
            hydrationChange = 2,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "sweetcorn", "boiled", "cooked", "prepared" }
        },

        new VegetableItemEntry
        {
            itemID = "sweetcorn_grilled",
            displayName = "Grilled Sweetcorn",
            icon = null,
            prefab = null,
            hungerChange = 5,
            hydrationChange = 1,
            weight = 0.3f,
            maxStackSize = 30,
            foodPoisoningChance = 0.002f,
            isCooked = true,
            canBeSliced = false,
            minSlices = 0,
            maxSlices = 0,
            canBeBoiled = false,
            canBeSteamed = false,
            canBeFried = false,
            canBeRoasted = false,
            canBeGrilled = false,
            secondaryItemID = null,
            minSecondaryYield = 0,
            maxSecondaryYield = 0,
            tags = new List<string> { "item", "food", "vegetable", "sweetcorn", "grilled", "cooked", "prepared" }
        },

        new VegetableItemEntry
{
    itemID = "sweetcorn_roasted",
    displayName = "Roasted Sweetcorn",
    icon = null,
    prefab = null,
    hungerChange = 5,
    hydrationChange = 1,
    weight = 0.3f,
    maxStackSize = 30,
    foodPoisoningChance = 0.002f,
    isCooked = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "sweetcorn", "roasted", "cooked", "prepared" }

    },
        new VegetableItemEntry
{
    itemID = "seaweed_raw",
    displayName = "Seaweed (Raw)",
    icon = null,
    prefab = null,
    hungerChange = 1,
    hydrationChange = 3,
    weight = 0.1f,
    maxStackSize = 50,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0.005f,
    parasiteChance = 0.008f,
    zombiePathogenChance = 0.0001f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = true,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "seaweed", "raw", "boilable", "hydrating", "aquatic", "plant" }
},

new VegetableItemEntry
{
    itemID = "seaweed_boiled",
    displayName = "Seaweed (Boiled)",
    icon = null,
    prefab = null,
    hungerChange = 2,
    hydrationChange = 2,
    weight = 0.1f,
    maxStackSize = 50,
    foodPoisoningChance = 0.003f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "seaweed", "boiled", "cooked", "hydrating", "aquatic", "plant" }
},

new VegetableItemEntry
{
    itemID = "seaweed_dried",
    displayName = "Seaweed (Dried)",
    icon = null,
    prefab = null,
    hungerChange = 2,
    hydrationChange = 0,
    weight = 0.05f,
    maxStackSize = 100,
    foodPoisoningChance = 0.002f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "seaweed", "dried", "cooked", "preserved", "aquatic", "plant" }
},
new VegetableItemEntry
{
    itemID = "mushroom_brown_raw",
    displayName = "Brown Mushroom",
    icon = null,
    prefab = null,
    hungerChange = 2,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.01f,
    salmonellaChance = 0.005f,
    parasiteChance = 0.006f,
    zombiePathogenChance = 0.0001f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeRoasted = true,
    canBeGrilled = true,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "brown", "raw", "boilable", "fryable", "roastable", "grillable", "fungus" }
},

new VegetableItemEntry
{
    itemID = "mushroom_white_raw",
    displayName = "White Mushroom",
    icon = null,
    prefab = null,
    hungerChange = 2,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.008f,
    salmonellaChance = 0.004f,
    parasiteChance = 0.005f,
    zombiePathogenChance = 0.0001f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = true,
    canBeSteamed = false,
    canBeFried = true,
    canBeRoasted = true,
    canBeGrilled = true,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "white", "raw", "boilable", "fryable", "roastable", "grillable", "fungus" }
},

new VegetableItemEntry
{
    itemID = "mushroom_spotted_raw",
    displayName = "Spotted Mushroom",
    icon = null,
    prefab = null,
    hungerChange = 1,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.03f,
    salmonellaChance = 0.01f,
    parasiteChance = 0.015f,
    zombiePathogenChance = 0.0005f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "spotted", "raw", "boilable", "fryable", "roastable", "grillable", "fungus", "suspicious" }
},
new VegetableItemEntry
{
    itemID = "mushroom_brown_boiled",
    displayName = "Brown Mushroom (Boiled)",
    icon = null,
    prefab = null,
    hungerChange = 3,
    hydrationChange = 2,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.002f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "brown", "boiled", "cooked", "fungus" }
},

new VegetableItemEntry
{
    itemID = "mushroom_brown_grilled",
    displayName = "Brown Mushroom (Grilled)",
    icon = null,
    prefab = null,
    hungerChange = 3,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.002f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "brown", "grilled", "cooked", "fungus" }
},

new VegetableItemEntry
{
    itemID = "mushroom_brown_fried",
    displayName = "Brown Mushroom (Fried)",
    icon = null,
    prefab = null,
    hungerChange = 4,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.001f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "brown", "fried", "cooked", "fungus" }
},

new VegetableItemEntry
{
    itemID = "mushroom_brown_roasted",
    displayName = "Brown Mushroom (Roasted)",
    icon = null,
    prefab = null,
    hungerChange = 4,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.001f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "brown", "roasted", "cooked", "fungus" }
},
new VegetableItemEntry
{
    itemID = "mushroom_white_boiled",
    displayName = "White Mushroom (Boiled)",
    icon = null,
    prefab = null,
    hungerChange = 3,
    hydrationChange = 2,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.0015f,
    salmonellaChance = 0.0008f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "white", "boiled", "cooked", "fungus" }
},

new VegetableItemEntry
{
    itemID = "mushroom_white_grilled",
    displayName = "White Mushroom (Grilled)",
    icon = null,
    prefab = null,
    hungerChange = 3,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.0015f,
    salmonellaChance = 0.0008f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "white", "grilled", "cooked", "fungus" }
},

new VegetableItemEntry
{
    itemID = "mushroom_white_fried",
    displayName = "White Mushroom (Fried)",
    icon = null,
    prefab = null,
    hungerChange = 4,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.001f,
    salmonellaChance = 0.0005f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "white", "fried", "cooked", "fungus" }
},


new VegetableItemEntry
{
    itemID = "mushroom_white_roasted",
    displayName = "White Mushroom (Roasted)",
    icon = null,
    prefab = null,
    hungerChange = 4,
    hydrationChange = 1,
    weight = 0.1f,
    maxStackSize = 40,
    foodPoisoningChance = 0.001f,
    salmonellaChance = 0.0005f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00005f,
    isCooked = true,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "mushroom", "white", "roasted", "cooked", "fungus" }
},
new VegetableItemEntry
{
    itemID = "peas_raw",
    displayName = "Peas (Raw)",
    icon = null,
    prefab = null,
    hungerChange = 2,
    hydrationChange = 2,
    weight = 0.1f,
    maxStackSize = 60,
    foodPoisoningChance = 0.005f,
    salmonellaChance = 0.002f,
    parasiteChance = 0.003f,
    zombiePathogenChance = 0.00005f,
    isCooked = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = true,
    canBeSteamed = true,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = "pea_seed",
    minSecondaryYield = 1,
    maxSecondaryYield = 3,
    tags = new List<string> { "item", "food", "vegetable", "peas", "raw", "boilable", "steamable", "plantable", "seed_source", "hydrating" }
},
new VegetableItemEntry
{
    itemID = "peas_boiled",
    displayName = "Peas (Boiled)",
    icon = null,
    prefab = null,
    hungerChange = 3,
    hydrationChange = 2,
    weight = 0.1f,
    maxStackSize = 60,
    foodPoisoningChance = 0.001f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00002f,
    isCooked = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "peas", "boiled", "cooked", "hydrating" }
},
new VegetableItemEntry
{
    itemID = "peas_steamed",
    displayName = "Peas (Steamed)",
    icon = null,
    prefab = null,
    hungerChange = 3,
    hydrationChange = 3,
    weight = 0.1f,
    maxStackSize = 60,
    foodPoisoningChance = 0.001f,
    salmonellaChance = 0.001f,
    parasiteChance = 0.001f,
    zombiePathogenChance = 0.00002f,
    isCooked = true,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string> { "item", "food", "vegetable", "peas", "steamed", "cooked", "hydrating" }
},
new VegetableItemEntry
{
    itemID = "pickle_fermented_unstable",
    displayName = "Pickle",
    icon = null,
    prefab = null,
    hungerChange = 5,
    hydrationChange = -1,
    weight = 0.3f,
    maxStackSize = 10,
    foodPoisoningChance = 0.002f,
    salmonellaChance = 0.0002f,
    parasiteChance = 0.0005f,
    zombiePathogenChance = 0.0001f,
    isCooked = false,
    canBeBoiled = false,
    canBeSteamed = false,
    canBeFried = false,
    canBeRoasted = false,
    canBeGrilled = false,
    canBeSliced = false,
    minSlices = 0,
    maxSlices = 0,
    secondaryItemID = null,
    minSecondaryYield = 0,
    maxSecondaryYield = 0,
    tags = new List<string>
    {
        "item", "food", "vegetable", "fermented", "pickle", "brined", "unstable", "egghunt", "suspicious", "legacy"
    }
}



};
}